name: 'Update Wiki-Website'
description: 'Copies all files from a wiki to a this (usually a GitHub pages) repository. Then moves Home.md to index.md, and creates a custom Home.md that permalinks to /.'
inputs:
  wiki-repository:
    description: 'Name of the source wiki repository: username/repo.wiki or organization/repo.wiki'
    required: true
  wiki-branch:
    description: '[Optional] Wiki repository branch, defaults to "master"'
    default: 'master'
    required: false
  user-email:
    description: 'Email for the git commit'
    required: true
  user-name:
    description: 'User name for the git commit.'
    required: true
  commit-message:
    description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
    default: 'Automated wiki-website update'
    required: false
  destination-repository:
    description: '[Optional] Name of the destination repository. Defaults to the this repository'
    default: ''
    required: false
  destination-branch:
    description: '[Optional] set target branch name for the destination repository. Defaults to "master" for historical reasons'
    default: 'master'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.wiki-repository }}
    - ${{ inputs.wiki-branch }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.destination-repository }}
    - ${{ inputs.destination-branch }}
branding:
  icon: 'git-commit'
  color: 'green'
